version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
      - ./mongoUser.js:/docker-entrypoint-initdb.d/mongoUser.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
volumes:
  mongo-volume: